# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
locale: "en-US"
title: "Adam Rozman - Personal Website"
email: admrozman@gmail.com
name: "Adam Rozman"
description: "PhD Candidate at Boston University specializing in aerodynamics and aeroacoustics modeling for multirotor vehicles."
baseurl: ""
image: "/images/headshot.JPG"
url: "https://adrozman.github.io"

# Site Author
author:
  name             : "Adam Rozman"
  avatar           : "/images/headshot.JPG"
  bio              : "PhD Candidate at Boston University specializing in aerodynamics and aeroacoustics modeling for multirotor vehicles."
  location         : "Boston, USA"
  employer         :
  pubmed           : 
  googlescholar    :
  email            :
  researchgate     : 
  github           : "adrozman"
  linkedin         : "arozman"
  orcid            : 


include:
  - .htaccess
  - _pages

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-redirect-from

defaults:
  - scope:
      path: "googlefe317d36a0316c62.html"
    values:
      sitemap: false
  - scope:
      path: "assets/Rozman_CV.pdf"
    values:
      sitemap: false

sass:
  sass_dir: _sass

# Seo
logo: "/images/headshot.JPG" 
social:
  name: Adam Rozman
  links:
    - https://github.com/adrozman
    - https://www.linkedin.com/in/arozman/

# Conversion
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false



# Markdown Processing
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  parse_block_html: true # default for kramdown is false. This will enable using Markdown links
